export enum CardLinks {
    EMap = "#/e-map",
    VideoWall = "#/video-wall",
    VideoSecurity = "#/video",
    SearchByFeatures = "#/person",
    SearchByPicture = "#/person/face-search-by-picture",
    BodyByFeatures = "#/person/body-search-by-feature",
    BodyByPicture = "#/person/body-search-by-picture",
    VehicleSearch = "#/vehicle",
    SearchByTrack = "#/vehicle/search-by-track",
    VehicleArming = "#/vehicle-arming",
    FaceArming = "#/face-arming",
    VehicleArmingAlarm = "#/vehicle-arming-alarm",
    FaceArmingAlarm = "#/face-arming-alarm",
    VehicleStatistics = "#/vehicle-statistics",
    FaceCaptureStatistics = "#/face-capture-statistics",
    Overview = "#/platform-info/overview",
    ReportAnalysis = "#/platform-info/report-analysis",
    VideoSecurityStatus = "#/video-surveillance",
    Log = "#/oper_log",
}